#!/usr/bin/env bash
# build.sh -- assemble the Atari 2600 FujiNet Lobby.
#
#   ./build.sh            the client:  build/lobby.bin
#   ./build.sh layout     the screen with no network: build/layout.bin
#
# The client is (N+1) x 2048 bytes: N 2K banks then the 2K fixed half, which
# is the layout vcs_set_image() expects. MAME's
# vcs_cart_slot_device::call_load() accepts only 4096/8192/16384/32768, so N
# is 1, 3, 7 or 15 and nothing between.
#
# Each bank carries its OWN copy of lblib and lbdisp: the high 2K of the
# window is the cartridge's mailbox in its entirety, so there is no fixed code
# region to share one from -- only the 220-byte tail, and the transport
# already fills it.
#
# The "FUJI" claim is stamped into the fixed half. Without it the cartridge
# treats the image as a game and the mailbox goes dead the moment it boots --
# which is exactly what has to happen for the game this lobby boots, and
# exactly what must not happen to the lobby itself.
#
# Env:
#   ENDPOINT=...       the lobby server (default https://lobby.fujinet.online/)
#   PLATFORM=...       the platform tag (default a2600)
#   FN2600=...         the cartridge tree
set -euo pipefail
cd "$(dirname "$0")"

FN2600="${FN2600:-$HOME/Workspace/fujinet-firmware/pico/atari-2600}"

if command -v asl >/dev/null 2>&1; then
    AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then
    AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else
    echo "build.sh: no Macroassembler AS found (tried PATH and ~/asl)" >&2
    exit 1
fi

mkdir -p build

# The equates are hand-mirrored from the firmware header, so check them BEFORE
# assembling anything: a drifted address assembles cleanly, runs, draws a
# screen, and silently talks to a page that decodes nothing.
#
# The blit and path equates go through --extra rather than that tool's shared
# table: a name listed there and missing from a client's .inc is a failure, so
# the table can only hold what EVERY client has.
#
# The FUJI device's command bytes are deliberately NOT in this list. They are
# command ids and live in the firmware's fujiCommandID.h, not in the mailbox
# header -- checkdefs only knows the one file, and listing a name it cannot
# find would fail the build for the wrong reason.
if [ -f "$FN2600/firmware/include/fuji_mailbox.h" ]; then
    python3 "$FN2600/tools/checkdefs.py" \
        "$FN2600/firmware/include/fuji_mailbox.h" src/fujinet.inc \
        --extra "FB_TEXT=FN_BLIT_TEXT,FB_PATH=FN_BLIT_PATH,FB_TCELL=FN_BLIT_TCELL,FH_BSL=FN_HOT_BLIT_SL,FH_BSH=FN_HOT_BLIT_SH,FH_BDL=FN_HOT_BLIT_DL,FH_BDH=FN_HOT_BLIT_DH,FH_BCNT=FN_HOT_BLIT_CNT,FH_BGO=FN_HOT_BLIT_GO,FP_POPCH=FN_PATH_POPCH,FP_SEL0=FN_PATH_SEL0,FP_SEL1=FN_PATH_SEL1,FP_SEL2=FN_PATH_SEL2,FP_SEL3=FN_PATH_SEL3,FP_SEED=FN_PATH_SEED,FP_COMMIT=FN_PATH_COMMIT,FNTROW=FN_T_ROWS,FNTCLH=FN_T_CELL_H"
else
    echo "build.sh: no fuji_mailbox.h at $FN2600 -- skipping the equate check" >&2
fi

# Regenerated every run, so a stale value cannot survive an environment
# change.
#
# NOTE THE ABSENT &appkey=. The server orders by game name ONLY when the
# request does not carry one: server/tx.go swaps to "ORDER BY Status,
# Lastping" the moment an appkey is supplied, and the whole header-on-change
# rendering collapses into noise. There is no filter this client wants badly
# enough to pay that.
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' \
        "${ENDPOINT:-https://lobby.fujinet.online/}"
    echo "        DB      0"
    printf 'UPLATF: DB      "%s"\n' "${PLATFORM:-a2600}"
    echo "        DB      0"
} > build/lobbyurl.inc

# p2bin ALWAYS emits its full -r range, so an over-long bank is truncated in
# SILENCE: the image builds, the size is right, checkrom passes, and the
# instructions past $17FF are simply gone -- and the next bank's bytes are
# what a jump into them finds. The assembler's own listing is the only thing
# that knows, so the build asks it.
bankfits() {
    python3 tools/checkbanks.py "build/$1.lst" "$2" "$1"
}

assemble() {
    local b=$1
    ( cd src && "$AS" -q -L -i . "$b.asm" )
    mv "src/$b.p" "build/$b.p"
    mv -f "src/$b.lst" "build/$b.lst" 2>/dev/null || true
}

stampclaim() {
    # The fixed half is the LAST 2K, so the claim's offset is a function of
    # the image size and cannot live in the source:
    #   (size - 2048) + (FN_R_CLAIM - $1800)
    local f=$1 size
    size=$(stat -c%s "$f")
    printf 'FUJI' | dd of="$f" bs=1 \
        seek=$((size - 0x800 + 0x0710)) conv=notrunc status=none
    echo "$f: $size bytes"
}

# ---------------- the layout ROM: one flat 4K image ----------------
if [ "${1:-}" = "layout" ]; then
    assemble layout
    bankfits layout $((0x1800))
    "$P2BIN" build/layout.p build/layout.bin -r '$1000-$1FFF' -l 0
    rm -f build/layout.p
    stampclaim build/layout.bin
    python3 "$FN2600/tools/checkrom.py" build/layout.bin
    exit 0
fi

# ---------------- the client: the banks and the fixed half ----------------
BANKS="lblist lbfetch lbname lbprep lbboot lbchat"

# THE TAIL IS ASSEMBLED FIRST, and not as tidiness: it holds the shared
# transport, and the banks reach it through build/tail.inc, which is generated
# from the addresses the tail actually assembled to. Nothing keeps a list of
# those by hand, because a hand-kept list of addresses goes stale in silence
# the moment a byte is added to any routine above them.
assemble lbtail
python3 tools/mktail.py build/lbtail.lst \
    FNRW,FNARM,FNCHK,FNBEG,FNPB,FNPW,FNGO,FNACK,\
FNROWA,FNCHR,FNENDR > build/tail.inc
tail -1 build/tail.inc | sed 's/^; */  tail: /'

parts=()
for b in $BANKS; do
    assemble "$b"
    bankfits "$b" $((0x1800))
    "$P2BIN" "build/$b.p" "build/$b.bin" -r '$1000-$17FF' -l 0
    rm -f "build/$b.p"
    parts+=("build/$b.bin")
done

"$P2BIN" build/lbtail.p build/lbtail.bin -r '$1800-$1FFF' -l 0
rm -f build/lbtail.p

# The spare bank. An image has to be one of four sizes and 16K is the one that
# fits six banks, so one exists whether or not it is wanted -- and it holds a
# stub back to bank 0, so a stray switch lands somewhere sensible rather than
# in a page of BRK.
assemble lbspare
bankfits lbspare $((0x1800))
"$P2BIN" build/lbspare.p build/lbspare.bin -r '$1000-$17FF' -l 0
rm -f build/lbspare.p

cat "${parts[@]}" build/lbspare.bin build/lbtail.bin > build/lobby.bin
rm -f "${parts[@]}" build/lbspare.bin build/lbtail.bin

stampclaim build/lobby.bin
python3 "$FN2600/tools/checkrom.py" build/lobby.bin
